# Generated by Django 2.2.1 on 2019-05-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addressid',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='customeraddr',
            old_name='customerid',
            new_name='customer_id',
        ),
    ]
