# Generated by Django 2.2.1 on 2019-05-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190523_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_id',
        ),
        migrations.DeleteModel(
            name='CustomerAddr',
        ),
    ]
