# Generated by Django 2.2.1 on 2019-05-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190523_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cutomer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
            preserve_default=False,
        ),
    ]
