# Generated by Django 2.2.1 on 2019-05-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_address_cutomer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='add2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='add3',
        ),
    ]
