# Generated by Django 2.2.1 on 2019-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20190524_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
