# Generated by Django 2.2.1 on 2019-05-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20190524_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='add1',
            new_name='address',
        ),
    ]
